//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TemperatureConverter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TemperatureConverter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przekroczono zero bezwzględne.
        /// </summary>
        internal static string errAbsoluteZero {
            get {
                return ResourceManager.GetString("errAbsoluteZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie można przeliczyć podanej wartości.
        /// </summary>
        internal static string errInvalidInput {
            get {
                return ResourceManager.GetString("errInvalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeliczyłeś temperaturę z Celsjusza.
        /// </summary>
        internal static string infoCelsiusCounted {
            get {
                return ResourceManager.GetString("infoCelsiusCounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeliczyłeś temperaturę z Farenheita.
        /// </summary>
        internal static string infoFarenheitCounted {
            get {
                return ResourceManager.GetString("infoFarenheitCounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przeliczyłeś temperaturę z Kelvina.
        /// </summary>
        internal static string infoKelvinCounted {
            get {
                return ResourceManager.GetString("infoKelvinCounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero bezwzględne.
        /// </summary>
        internal static string strAbsoluteZero {
            get {
                return ResourceManager.GetString("strAbsoluteZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Średnia temperature ciała człowieka.
        /// </summary>
        internal static string strAvgBodyTemperature {
            get {
                return ResourceManager.GetString("strAvgBodyTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrzenie wody.
        /// </summary>
        internal static string strBoilingWater {
            get {
                return ResourceManager.GetString("strBoilingWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero Farenheita.
        /// </summary>
        internal static string strFarenheitZero {
            get {
                return ResourceManager.GetString("strFarenheitZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zamarzanie wody.
        /// </summary>
        internal static string strFrozenWater {
            get {
                return ResourceManager.GetString("strFrozenWater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperatura efektywna powierzchni słońca.
        /// </summary>
        internal static string strSunTemperature {
            get {
                return ResourceManager.GetString("strSunTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topnienie tytanu.
        /// </summary>
        internal static string strTitanMelting {
            get {
                return ResourceManager.GetString("strTitanMelting", resourceCulture);
            }
        }
    }
}
